name: Publish Vue Nottingham JSON

on:
  schedule:
    - cron: "0 */3 * * *" # every 3 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install playwright
      - run: node scrape.mjs
      - uses: actions/upload-artifact@v3
        with:
          name: vue-json
          path: vue-nottingham.json
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
